# Generated by Django 5.0.4 on 2024-09-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
