# Generated by Django 5.0.4 on 2024-04-30 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0004_session_attendee'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='session',
            name='capacity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
