# Generated by Django 5.0.4 on 2024-05-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0006_alter_attendee_user_event_alter_attendee_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
