# Generated by Django 5.0.4 on 2024-05-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0007_attendee_first_name_attendee_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='session',
            new_name='event',
        ),
    ]
