# Generated by Django 5.0.4 on 2024-05-03 05:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0008_rename_session_attendee_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='pax',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
