# Generated by Django 5.0.4 on 2024-05-03 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0009_attendee_pax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='pax',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
