# Generated by Django 5.0.4 on 2024-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0010_alter_attendee_pax'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='guest_id',
            field=models.IntegerField(default=None),
        ),
    ]
