# Generated by Django 5.0.4 on 2024-05-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0012_alter_attendee_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='guest_id',
            field=models.UUIDField(null=True),
        ),
    ]
