# Generated by Django 5.0.4 on 2024-05-05 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0013_alter_attendee_guest_id'),
        migrations.swappable_dependency(settings.GUEST_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='guest_id',
        ),
        migrations.AddField(
            model_name='attendee',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to=settings.GUEST_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
    ]
