# Generated by Django 5.0.4 on 2024-05-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floral_jamming', '0024_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
